//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.17 at 06:33:17 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ti.bfh.ch/euromillions/")
package jaxb_lotterytypes;
